### ISSUE TITLE
Application freezes on simple scenario

### ISSUE THREAD

**Issue by kirhgoff** [kirhgoff/morphoid#2]
gradle run -PappArgs="['simple']"

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at org.kirhgoff.morphoid.engine.HerbivoreSoul.shroom(Psyche.scala:52)
        at org.kirhgoff.morphoid.engine.HerbivoreSoul.$anonfun$act$1(Psyche.scala:43)
        at org.kirhgoff.morphoid.engine.HerbivoreSoul.$anonfun$act$1$adapted(Psyche.scala:43)
        at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:111)
        at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:108)
        at scala.collection.immutable.List.find(List.scala:86)
        at org.kirhgoff.morphoid.engine.HerbivoreSoul.act(Psyche.scala:43)
        at org.kirhgoff.morphoid.engine.MorphoidEngine.$anonfun$tick$3(MorphoidEngine.scala:95)
        at org.kirhgoff.morphoid.engine.MorphoidEngine.$anonfun$tick$3$adapted(MorphoidEngine.scala:93)
        at scala.collection.immutable.List.foreach(List.scala:378)
        at org.kirhgoff.morphoid.engine.MorphoidEngine.tick(MorphoidEngine.scala:93)
        at org.kirhgoff.morphoid.MorphoidApp.lambda$start$0(MorphoidApp.java:79)
        at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
        at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
        at javafx.animation.Timeline.impl_playTo(Timeline.java:176)
        at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
        at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
        at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
        at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
        at java.security.AccessController.doPrivileged(Native Method)
        at javafx.animation.Animation$1.timePulse(Animation.java:185)
        at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
        at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by kirhgoff** [comment]
Fixed
